### ISSUE TITLE
Pyota library error after compiling the file to exe

### ISSUE THREAD

**Issue by policmajsterdev** [iotaledger-archive/iota.py#341]
## Bug description

Error compiling the game to the exe file

## Version

Which version of the library are you running?

- PyOTA Version: 2.1.0
- Python Version: 3.8.5

## IOTA network

Which node are you connected to and which IOTA network is it in?

- Node URL:
- Network: Hornet

## Environment

What operating system are you using?

- Operating system: Windows 10 Pro

## Expected behaviour

I am looking for a solution or workaround for a problem.

## Actual behaviour

I am creating a game using the pyota library, where the player has the save game function in DLT IOTA. 
When I run the game from the PyCharm development environment, everything works 
(https://www.youtube.com/watch?v=Bqrc_I3bXU0&feature=emb_title)
 When I compile the game with PyInstaller, the game does not start and I get an error.

## Errors

```
Traceback (most recent call last):
  File "gam.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\python\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "iotaconn.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\python\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\iota\__init__.py", line 38, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\python\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\iota\api.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\python\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\iota\commands\__init__.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\python\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\filters\__init__.py", line 3, in <module>
  File "site-packages\pkg_resources\__init__.py", line 899, in require
  File "site-packages\pkg_resources\__init__.py", line 785, in resolve
pkg_resources.DistributionNotFound: The 'phx-filters' distribution was not found and is required by the application
[2156] Failed to execute script gam
```

**Comment by todofixthis** [comment]
Hi @policmajsterdev thanks for reporting this issue!

The key line from the traceback is this one:
```
pkg_resources.DistributionNotFound: The 'phx-filters' distribution was not found and is required by the application
```

These pages may be relevant to the issue you're experiencing:
* <https://pyinstaller.readthedocs.io/en/stable/operating-mode.html#analysis-finding-the-files-your-program-needs>
* <https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html#helping-pyinstaller-find-modules>

Could you post the exact `pyinstaller` command you are running to create the exe file?

**Comment by policmajsterdev** [comment]
Thank you for your answer. My command looks like this:
`pyinstaller --noconfirm --onefile --console --add-data "C:/Users/eimea/Desktop/gfx/game/data;data/"  "C:/Users/eimea/Desktop/gfx/game/gam.py"`

**Comment by todofixthis** [comment]
🤔 I note that the same issue occurred in #193 — I wonder if this is because the `phx-filters` lib has a self-referential `require` statement:
https://github.com/todofixthis/filters/blob/2.0.2/filters/__init__.py#L3

This is a common practice, so I imagine that pyinstaller users will run into this issue from time to time.

Possibly one of the answers to this StackOverflow post may be helpful here:
https://stackoverflow.com/q/40076795/5568265

Also, double-check that you have the most up-to-date version of pyinstaller; see https://github.com/pyinstaller/pyinstaller/issues/1515#issuecomment-177372695

**Comment by policmajsterdev** [comment]
Thanks for your help but I still have a problem. I uninstalled the entire python environment several times, installed it in various combinations, and then nothing.
My version of pyinstaller is 4.1.
I noticed that the boot always stops in the same place when importing a module using 'pyota'.

As you wrote, the problem is somewhere here:
`__version__ = require('phx-filters')[0].version`

Unfortunately, I'm not that advanced in python and I don't know what to do next.
Thank you for your help, I will keep trying.

**Comment by todofixthis** [comment]
No worries; I think we're on the right track.  Many of the answers and linked Github issues on the above StackOverflow page seem to point to using a PyInstaller hook to resolve this issue.  I think something like this will address the issue:

1. Find or create the file `hooks-phx-filters.py` (you'll need to do a bit of experimentation/research to find the right location; <https://stackoverflow.com/a/52898981/5568265> suggests a possible location).
    * Discovering where the hooks files get created will teach you a bit about how PyInstaller works under-the-hood, and if you're unable to determine the correct location you can alternatively specify `--additional-hooks-dir` to load hooks from a directory of your choosing (see <https://stackoverflow.com/a/28023347/5568265> for more info).
2. Add the following content to `hooks-phx-filters.py`:
    ```py
    from PyInstaller.utils.hooks import copy_metadata
    datas = copy_metadata('phx-filters')
    ```

Let me know if you're able to get this working; I see that it is possible to [add PyInstaller hooks directly to a package](https://pyinstaller.readthedocs.io/en/stable/hooks.html#provide-hooks-with-package) — if the custom hook fixes the issue I'll see about adding it to the `phx-filters` library 😺

**Comment by policmajsterdev** [comment]
Hello! I did as you wrote and it seems that something has moved :)
But I got another error:

```
Traceback (most recent call last): 
File "gam.py", line 12, in <module>
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked

  File "c:\pythonx\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)

  File "iotaconn.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked

  File "c:\pythonx\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)

  File "iota\__init__.py", line 43, in <module>
  File "pkg_resources\__init__.py", line 899, in require
  File "pkg_resources\__init__.py", line 785, in resolve

pkg_resources.DistributionNotFound: The 'PyOTA' distribution was not found and is required by the application
[13752] Failed to execute script gam
```

**But..**
**For PyOTA I did exactly like for phx-filters and it works!**

```py
datas = copy_metadata('phx-filters')
datas += copy_metadata('PyOTA')
```

Thank you very much!
**Greetings! :)**

**Comment by todofixthis** [comment]
Sweeeet as.  Great to see you got it working!  I'll make a note of this, so that we can make future versions of PyOTA (and phx-filters 😁) PyInstaller-compatible out-of-the-box.
